package com.salk.best.product.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.salk.best.domain.Product;
import com.salk.best.domain.ProductExample;

public interface ProductMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table product
	 * 
	 * @mbggenerated
	 */
	int countByExample(ProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table product
	 * 
	 * @mbggenerated
	 */
	int deleteByExample(ProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table product
	 * 
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table product
	 * 
	 * @mbggenerated
	 */
	int insert(Product record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table product
	 * 
	 * @mbggenerated
	 */
	int insertSelective(Product record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table product
	 * 
	 * @mbggenerated
	 */
	List<Product> selectByExample(ProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table product
	 * 
	 * @mbggenerated
	 */
	Product selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table product
	 * 
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Product record, @Param("example") ProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table product
	 * 
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Product record, @Param("example") ProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table product
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Product record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table product
	 * 
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Product record);

	int updateByProd(Product record);

	int deleteByPrimaryKeys(@Param("ids") String[] ids);

	boolean updateProductNums(@Param("id") String id, @Param("nums") int nums);

	List<Product> getProductsByPage(ProductExample example);

	Integer countProdByExample(ProductExample example);

}