package com.salk.best.domain;

import java.util.Date;

public class Product {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.prod_no
	 * @mbggenerated
	 */
	private String prodNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.prod_size
	 * @mbggenerated
	 */
	private String prodSize;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.prod_type
	 * @mbggenerated
	 */
	private String prodType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.prod_color
	 * @mbggenerated
	 */
	private String prodColor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.adder_name
	 * @mbggenerated
	 */
	private String adderName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.add_time
	 * @mbggenerated
	 */
	private Date addTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.is_lock
	 * @mbggenerated
	 */
	private String isLock;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.nums
	 * @mbggenerated
	 */
	private Integer nums;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.prod_name
	 * @mbggenerated
	 */
	private String prodName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.updater_name
	 * @mbggenerated
	 */
	private String updaterName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.update_no
	 * @mbggenerated
	 */
	private String updateNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.update_time
	 * @mbggenerated
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.adder_no
	 * @mbggenerated
	 */
	private String adderNo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.id
	 * @return  the value of product.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.id
	 * @param id  the value for product.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.prod_no
	 * @return  the value of product.prod_no
	 * @mbggenerated
	 */
	public String getProdNo() {
		return prodNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.prod_no
	 * @param prodNo  the value for product.prod_no
	 * @mbggenerated
	 */
	public void setProdNo(String prodNo) {
		this.prodNo = prodNo == null ? null : prodNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.prod_size
	 * @return  the value of product.prod_size
	 * @mbggenerated
	 */
	public String getProdSize() {
		return prodSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.prod_size
	 * @param prodSize  the value for product.prod_size
	 * @mbggenerated
	 */
	public void setProdSize(String prodSize) {
		this.prodSize = prodSize == null ? null : prodSize.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.prod_type
	 * @return  the value of product.prod_type
	 * @mbggenerated
	 */
	public String getProdType() {
		return prodType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.prod_type
	 * @param prodType  the value for product.prod_type
	 * @mbggenerated
	 */
	public void setProdType(String prodType) {
		this.prodType = prodType == null ? null : prodType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.prod_color
	 * @return  the value of product.prod_color
	 * @mbggenerated
	 */
	public String getProdColor() {
		return prodColor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.prod_color
	 * @param prodColor  the value for product.prod_color
	 * @mbggenerated
	 */
	public void setProdColor(String prodColor) {
		this.prodColor = prodColor == null ? null : prodColor.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.adder_name
	 * @return  the value of product.adder_name
	 * @mbggenerated
	 */
	public String getAdderName() {
		return adderName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.adder_name
	 * @param adderName  the value for product.adder_name
	 * @mbggenerated
	 */
	public void setAdderName(String adderName) {
		this.adderName = adderName == null ? null : adderName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.add_time
	 * @return  the value of product.add_time
	 * @mbggenerated
	 */
	public Date getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.add_time
	 * @param addTime  the value for product.add_time
	 * @mbggenerated
	 */
	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.is_lock
	 * @return  the value of product.is_lock
	 * @mbggenerated
	 */
	public String getIsLock() {
		return isLock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.is_lock
	 * @param isLock  the value for product.is_lock
	 * @mbggenerated
	 */
	public void setIsLock(String isLock) {
		this.isLock = isLock == null ? null : isLock.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.nums
	 * @return  the value of product.nums
	 * @mbggenerated
	 */
	public Integer getNums() {
		return nums;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.nums
	 * @param nums  the value for product.nums
	 * @mbggenerated
	 */
	public void setNums(Integer nums) {
		this.nums = nums;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.prod_name
	 * @return  the value of product.prod_name
	 * @mbggenerated
	 */
	public String getProdName() {
		return prodName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.prod_name
	 * @param prodName  the value for product.prod_name
	 * @mbggenerated
	 */
	public void setProdName(String prodName) {
		this.prodName = prodName == null ? null : prodName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.updater_name
	 * @return  the value of product.updater_name
	 * @mbggenerated
	 */
	public String getUpdaterName() {
		return updaterName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.updater_name
	 * @param updaterName  the value for product.updater_name
	 * @mbggenerated
	 */
	public void setUpdaterName(String updaterName) {
		this.updaterName = updaterName == null ? null : updaterName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.update_no
	 * @return  the value of product.update_no
	 * @mbggenerated
	 */
	public String getUpdateNo() {
		return updateNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.update_no
	 * @param updateNo  the value for product.update_no
	 * @mbggenerated
	 */
	public void setUpdateNo(String updateNo) {
		this.updateNo = updateNo == null ? null : updateNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.update_time
	 * @return  the value of product.update_time
	 * @mbggenerated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.update_time
	 * @param updateTime  the value for product.update_time
	 * @mbggenerated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.adder_no
	 * @return  the value of product.adder_no
	 * @mbggenerated
	 */
	public String getAdderNo() {
		return adderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.adder_no
	 * @param adderNo  the value for product.adder_no
	 * @mbggenerated
	 */
	public void setAdderNo(String adderNo) {
		this.adderNo = adderNo == null ? null : adderNo.trim();
	}
}