package com.salk.best.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProductExample {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table product
	 * 
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table product
	 * 
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table product
	 * 
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table product
	 * 
	 * @mbggenerated
	 */
	private Page page;

	public ProductExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table product
	 * 
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table product
	 * 
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table product
	 * 
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table product
	 * 
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table product
	 * 
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table product
	 * 
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table product
	 * 
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table product
	 * 
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table product
	 * 
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table product
	 * 
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table product
	 * 
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andProdNoIsNull() {
			addCriterion("prod_no is null");
			return (Criteria) this;
		}

		public Criteria andProdNoIsNotNull() {
			addCriterion("prod_no is not null");
			return (Criteria) this;
		}

		public Criteria andProdNoEqualTo(String value) {
			addCriterion("prod_no =", value, "prodNo");
			return (Criteria) this;
		}

		public Criteria andProdNoNotEqualTo(String value) {
			addCriterion("prod_no <>", value, "prodNo");
			return (Criteria) this;
		}

		public Criteria andProdNoGreaterThan(String value) {
			addCriterion("prod_no >", value, "prodNo");
			return (Criteria) this;
		}

		public Criteria andProdNoGreaterThanOrEqualTo(String value) {
			addCriterion("prod_no >=", value, "prodNo");
			return (Criteria) this;
		}

		public Criteria andProdNoLessThan(String value) {
			addCriterion("prod_no <", value, "prodNo");
			return (Criteria) this;
		}

		public Criteria andProdNoLessThanOrEqualTo(String value) {
			addCriterion("prod_no <=", value, "prodNo");
			return (Criteria) this;
		}

		public Criteria andProdNoLike(String value) {
			addCriterion("prod_no like", value, "prodNo");
			return (Criteria) this;
		}

		public Criteria andProdNoNotLike(String value) {
			addCriterion("prod_no not like", value, "prodNo");
			return (Criteria) this;
		}

		public Criteria andProdNoIn(List<String> values) {
			addCriterion("prod_no in", values, "prodNo");
			return (Criteria) this;
		}

		public Criteria andProdNoNotIn(List<String> values) {
			addCriterion("prod_no not in", values, "prodNo");
			return (Criteria) this;
		}

		public Criteria andProdNoBetween(String value1, String value2) {
			addCriterion("prod_no between", value1, value2, "prodNo");
			return (Criteria) this;
		}

		public Criteria andProdNoNotBetween(String value1, String value2) {
			addCriterion("prod_no not between", value1, value2, "prodNo");
			return (Criteria) this;
		}

		public Criteria andProdSizeIsNull() {
			addCriterion("prod_size is null");
			return (Criteria) this;
		}

		public Criteria andProdSizeIsNotNull() {
			addCriterion("prod_size is not null");
			return (Criteria) this;
		}

		public Criteria andProdSizeEqualTo(String value) {
			addCriterion("prod_size =", value, "prodSize");
			return (Criteria) this;
		}

		public Criteria andProdSizeNotEqualTo(String value) {
			addCriterion("prod_size <>", value, "prodSize");
			return (Criteria) this;
		}

		public Criteria andProdSizeGreaterThan(String value) {
			addCriterion("prod_size >", value, "prodSize");
			return (Criteria) this;
		}

		public Criteria andProdSizeGreaterThanOrEqualTo(String value) {
			addCriterion("prod_size >=", value, "prodSize");
			return (Criteria) this;
		}

		public Criteria andProdSizeLessThan(String value) {
			addCriterion("prod_size <", value, "prodSize");
			return (Criteria) this;
		}

		public Criteria andProdSizeLessThanOrEqualTo(String value) {
			addCriterion("prod_size <=", value, "prodSize");
			return (Criteria) this;
		}

		public Criteria andProdSizeLike(String value) {
			addCriterion("prod_size like", value, "prodSize");
			return (Criteria) this;
		}

		public Criteria andProdSizeNotLike(String value) {
			addCriterion("prod_size not like", value, "prodSize");
			return (Criteria) this;
		}

		public Criteria andProdSizeIn(List<String> values) {
			addCriterion("prod_size in", values, "prodSize");
			return (Criteria) this;
		}

		public Criteria andProdSizeNotIn(List<String> values) {
			addCriterion("prod_size not in", values, "prodSize");
			return (Criteria) this;
		}

		public Criteria andProdSizeBetween(String value1, String value2) {
			addCriterion("prod_size between", value1, value2, "prodSize");
			return (Criteria) this;
		}

		public Criteria andProdSizeNotBetween(String value1, String value2) {
			addCriterion("prod_size not between", value1, value2, "prodSize");
			return (Criteria) this;
		}

		public Criteria andProdTypeIsNull() {
			addCriterion("prod_type is null");
			return (Criteria) this;
		}

		public Criteria andProdTypeIsNotNull() {
			addCriterion("prod_type is not null");
			return (Criteria) this;
		}

		public Criteria andProdTypeEqualTo(String value) {
			addCriterion("prod_type =", value, "prodType");
			return (Criteria) this;
		}

		public Criteria andProdTypeNotEqualTo(String value) {
			addCriterion("prod_type <>", value, "prodType");
			return (Criteria) this;
		}

		public Criteria andProdTypeGreaterThan(String value) {
			addCriterion("prod_type >", value, "prodType");
			return (Criteria) this;
		}

		public Criteria andProdTypeGreaterThanOrEqualTo(String value) {
			addCriterion("prod_type >=", value, "prodType");
			return (Criteria) this;
		}

		public Criteria andProdTypeLessThan(String value) {
			addCriterion("prod_type <", value, "prodType");
			return (Criteria) this;
		}

		public Criteria andProdTypeLessThanOrEqualTo(String value) {
			addCriterion("prod_type <=", value, "prodType");
			return (Criteria) this;
		}

		public Criteria andProdTypeLike(String value) {
			addCriterion("prod_type like", value, "prodType");
			return (Criteria) this;
		}

		public Criteria andProdTypeNotLike(String value) {
			addCriterion("prod_type not like", value, "prodType");
			return (Criteria) this;
		}

		public Criteria andProdTypeIn(List<String> values) {
			addCriterion("prod_type in", values, "prodType");
			return (Criteria) this;
		}

		public Criteria andProdTypeNotIn(List<String> values) {
			addCriterion("prod_type not in", values, "prodType");
			return (Criteria) this;
		}

		public Criteria andProdTypeBetween(String value1, String value2) {
			addCriterion("prod_type between", value1, value2, "prodType");
			return (Criteria) this;
		}

		public Criteria andProdTypeNotBetween(String value1, String value2) {
			addCriterion("prod_type not between", value1, value2, "prodType");
			return (Criteria) this;
		}

		public Criteria andProdColorIsNull() {
			addCriterion("prod_color is null");
			return (Criteria) this;
		}

		public Criteria andProdColorIsNotNull() {
			addCriterion("prod_color is not null");
			return (Criteria) this;
		}

		public Criteria andProdColorEqualTo(String value) {
			addCriterion("prod_color =", value, "prodColor");
			return (Criteria) this;
		}

		public Criteria andProdColorNotEqualTo(String value) {
			addCriterion("prod_color <>", value, "prodColor");
			return (Criteria) this;
		}

		public Criteria andProdColorGreaterThan(String value) {
			addCriterion("prod_color >", value, "prodColor");
			return (Criteria) this;
		}

		public Criteria andProdColorGreaterThanOrEqualTo(String value) {
			addCriterion("prod_color >=", value, "prodColor");
			return (Criteria) this;
		}

		public Criteria andProdColorLessThan(String value) {
			addCriterion("prod_color <", value, "prodColor");
			return (Criteria) this;
		}

		public Criteria andProdColorLessThanOrEqualTo(String value) {
			addCriterion("prod_color <=", value, "prodColor");
			return (Criteria) this;
		}

		public Criteria andProdColorLike(String value) {
			addCriterion("prod_color like", value, "prodColor");
			return (Criteria) this;
		}

		public Criteria andProdColorNotLike(String value) {
			addCriterion("prod_color not like", value, "prodColor");
			return (Criteria) this;
		}

		public Criteria andProdColorIn(List<String> values) {
			addCriterion("prod_color in", values, "prodColor");
			return (Criteria) this;
		}

		public Criteria andProdColorNotIn(List<String> values) {
			addCriterion("prod_color not in", values, "prodColor");
			return (Criteria) this;
		}

		public Criteria andProdColorBetween(String value1, String value2) {
			addCriterion("prod_color between", value1, value2, "prodColor");
			return (Criteria) this;
		}

		public Criteria andProdColorNotBetween(String value1, String value2) {
			addCriterion("prod_color not between", value1, value2, "prodColor");
			return (Criteria) this;
		}

		public Criteria andAdderNameIsNull() {
			addCriterion("adder_name is null");
			return (Criteria) this;
		}

		public Criteria andAdderNameIsNotNull() {
			addCriterion("adder_name is not null");
			return (Criteria) this;
		}

		public Criteria andAdderNameEqualTo(String value) {
			addCriterion("adder_name =", value, "adderName");
			return (Criteria) this;
		}

		public Criteria andAdderNameNotEqualTo(String value) {
			addCriterion("adder_name <>", value, "adderName");
			return (Criteria) this;
		}

		public Criteria andAdderNameGreaterThan(String value) {
			addCriterion("adder_name >", value, "adderName");
			return (Criteria) this;
		}

		public Criteria andAdderNameGreaterThanOrEqualTo(String value) {
			addCriterion("adder_name >=", value, "adderName");
			return (Criteria) this;
		}

		public Criteria andAdderNameLessThan(String value) {
			addCriterion("adder_name <", value, "adderName");
			return (Criteria) this;
		}

		public Criteria andAdderNameLessThanOrEqualTo(String value) {
			addCriterion("adder_name <=", value, "adderName");
			return (Criteria) this;
		}

		public Criteria andAdderNameLike(String value) {
			addCriterion("adder_name like", value, "adderName");
			return (Criteria) this;
		}

		public Criteria andAdderNameNotLike(String value) {
			addCriterion("adder_name not like", value, "adderName");
			return (Criteria) this;
		}

		public Criteria andAdderNameIn(List<String> values) {
			addCriterion("adder_name in", values, "adderName");
			return (Criteria) this;
		}

		public Criteria andAdderNameNotIn(List<String> values) {
			addCriterion("adder_name not in", values, "adderName");
			return (Criteria) this;
		}

		public Criteria andAdderNameBetween(String value1, String value2) {
			addCriterion("adder_name between", value1, value2, "adderName");
			return (Criteria) this;
		}

		public Criteria andAdderNameNotBetween(String value1, String value2) {
			addCriterion("adder_name not between", value1, value2, "adderName");
			return (Criteria) this;
		}

		public Criteria andAddTimeIsNull() {
			addCriterion("add_time is null");
			return (Criteria) this;
		}

		public Criteria andAddTimeIsNotNull() {
			addCriterion("add_time is not null");
			return (Criteria) this;
		}

		public Criteria andAddTimeEqualTo(Date value) {
			addCriterion("add_time =", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeNotEqualTo(Date value) {
			addCriterion("add_time <>", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeGreaterThan(Date value) {
			addCriterion("add_time >", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("add_time >=", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeLessThan(Date value) {
			addCriterion("add_time <", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeLessThanOrEqualTo(Date value) {
			addCriterion("add_time <=", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeIn(List<Date> values) {
			addCriterion("add_time in", values, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeNotIn(List<Date> values) {
			addCriterion("add_time not in", values, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeBetween(Date value1, Date value2) {
			addCriterion("add_time between", value1, value2, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeNotBetween(Date value1, Date value2) {
			addCriterion("add_time not between", value1, value2, "addTime");
			return (Criteria) this;
		}

		public Criteria andIsLockIsNull() {
			addCriterion("is_lock is null");
			return (Criteria) this;
		}

		public Criteria andIsLockIsNotNull() {
			addCriterion("is_lock is not null");
			return (Criteria) this;
		}

		public Criteria andIsLockEqualTo(String value) {
			addCriterion("is_lock =", value, "isLock");
			return (Criteria) this;
		}

		public Criteria andIsLockNotEqualTo(String value) {
			addCriterion("is_lock <>", value, "isLock");
			return (Criteria) this;
		}

		public Criteria andIsLockGreaterThan(String value) {
			addCriterion("is_lock >", value, "isLock");
			return (Criteria) this;
		}

		public Criteria andIsLockGreaterThanOrEqualTo(String value) {
			addCriterion("is_lock >=", value, "isLock");
			return (Criteria) this;
		}

		public Criteria andIsLockLessThan(String value) {
			addCriterion("is_lock <", value, "isLock");
			return (Criteria) this;
		}

		public Criteria andIsLockLessThanOrEqualTo(String value) {
			addCriterion("is_lock <=", value, "isLock");
			return (Criteria) this;
		}

		public Criteria andIsLockLike(String value) {
			addCriterion("is_lock like", value, "isLock");
			return (Criteria) this;
		}

		public Criteria andIsLockNotLike(String value) {
			addCriterion("is_lock not like", value, "isLock");
			return (Criteria) this;
		}

		public Criteria andIsLockIn(List<String> values) {
			addCriterion("is_lock in", values, "isLock");
			return (Criteria) this;
		}

		public Criteria andIsLockNotIn(List<String> values) {
			addCriterion("is_lock not in", values, "isLock");
			return (Criteria) this;
		}

		public Criteria andIsLockBetween(String value1, String value2) {
			addCriterion("is_lock between", value1, value2, "isLock");
			return (Criteria) this;
		}

		public Criteria andIsLockNotBetween(String value1, String value2) {
			addCriterion("is_lock not between", value1, value2, "isLock");
			return (Criteria) this;
		}

		public Criteria andNumsIsNull() {
			addCriterion("nums is null");
			return (Criteria) this;
		}

		public Criteria andNumsIsNotNull() {
			addCriterion("nums is not null");
			return (Criteria) this;
		}

		public Criteria andNumsEqualTo(Integer value) {
			addCriterion("nums =", value, "nums");
			return (Criteria) this;
		}

		public Criteria andNumsNotEqualTo(Integer value) {
			addCriterion("nums <>", value, "nums");
			return (Criteria) this;
		}

		public Criteria andNumsGreaterThan(Integer value) {
			addCriterion("nums >", value, "nums");
			return (Criteria) this;
		}

		public Criteria andNumsGreaterThanOrEqualTo(Integer value) {
			addCriterion("nums >=", value, "nums");
			return (Criteria) this;
		}

		public Criteria andNumsLessThan(Integer value) {
			addCriterion("nums <", value, "nums");
			return (Criteria) this;
		}

		public Criteria andNumsLessThanOrEqualTo(Integer value) {
			addCriterion("nums <=", value, "nums");
			return (Criteria) this;
		}

		public Criteria andNumsIn(List<Integer> values) {
			addCriterion("nums in", values, "nums");
			return (Criteria) this;
		}

		public Criteria andNumsNotIn(List<Integer> values) {
			addCriterion("nums not in", values, "nums");
			return (Criteria) this;
		}

		public Criteria andNumsBetween(Integer value1, Integer value2) {
			addCriterion("nums between", value1, value2, "nums");
			return (Criteria) this;
		}

		public Criteria andNumsNotBetween(Integer value1, Integer value2) {
			addCriterion("nums not between", value1, value2, "nums");
			return (Criteria) this;
		}

		public Criteria andProdNameIsNull() {
			addCriterion("prod_name is null");
			return (Criteria) this;
		}

		public Criteria andProdNameIsNotNull() {
			addCriterion("prod_name is not null");
			return (Criteria) this;
		}

		public Criteria andProdNameEqualTo(String value) {
			addCriterion("prod_name =", value, "prodName");
			return (Criteria) this;
		}

		public Criteria andProdNameNotEqualTo(String value) {
			addCriterion("prod_name <>", value, "prodName");
			return (Criteria) this;
		}

		public Criteria andProdNameGreaterThan(String value) {
			addCriterion("prod_name >", value, "prodName");
			return (Criteria) this;
		}

		public Criteria andProdNameGreaterThanOrEqualTo(String value) {
			addCriterion("prod_name >=", value, "prodName");
			return (Criteria) this;
		}

		public Criteria andProdNameLessThan(String value) {
			addCriterion("prod_name <", value, "prodName");
			return (Criteria) this;
		}

		public Criteria andProdNameLessThanOrEqualTo(String value) {
			addCriterion("prod_name <=", value, "prodName");
			return (Criteria) this;
		}

		public Criteria andProdNameLike(String value) {
			addCriterion("prod_name like", value, "prodName");
			return (Criteria) this;
		}

		public Criteria andProdNameNotLike(String value) {
			addCriterion("prod_name not like", value, "prodName");
			return (Criteria) this;
		}

		public Criteria andProdNameIn(List<String> values) {
			addCriterion("prod_name in", values, "prodName");
			return (Criteria) this;
		}

		public Criteria andProdNameNotIn(List<String> values) {
			addCriterion("prod_name not in", values, "prodName");
			return (Criteria) this;
		}

		public Criteria andProdNameBetween(String value1, String value2) {
			addCriterion("prod_name between", value1, value2, "prodName");
			return (Criteria) this;
		}

		public Criteria andProdNameNotBetween(String value1, String value2) {
			addCriterion("prod_name not between", value1, value2, "prodName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameIsNull() {
			addCriterion("updater_name is null");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameIsNotNull() {
			addCriterion("updater_name is not null");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameEqualTo(String value) {
			addCriterion("updater_name =", value, "updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameNotEqualTo(String value) {
			addCriterion("updater_name <>", value, "updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameGreaterThan(String value) {
			addCriterion("updater_name >", value, "updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameGreaterThanOrEqualTo(String value) {
			addCriterion("updater_name >=", value, "updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameLessThan(String value) {
			addCriterion("updater_name <", value, "updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameLessThanOrEqualTo(String value) {
			addCriterion("updater_name <=", value, "updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameLike(String value) {
			addCriterion("updater_name like", value, "updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameNotLike(String value) {
			addCriterion("updater_name not like", value, "updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameIn(List<String> values) {
			addCriterion("updater_name in", values, "updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameNotIn(List<String> values) {
			addCriterion("updater_name not in", values, "updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameBetween(String value1, String value2) {
			addCriterion("updater_name between", value1, value2, "updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameNotBetween(String value1, String value2) {
			addCriterion("updater_name not between", value1, value2, "updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdateNoIsNull() {
			addCriterion("update_no is null");
			return (Criteria) this;
		}

		public Criteria andUpdateNoIsNotNull() {
			addCriterion("update_no is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateNoEqualTo(String value) {
			addCriterion("update_no =", value, "updateNo");
			return (Criteria) this;
		}

		public Criteria andUpdateNoNotEqualTo(String value) {
			addCriterion("update_no <>", value, "updateNo");
			return (Criteria) this;
		}

		public Criteria andUpdateNoGreaterThan(String value) {
			addCriterion("update_no >", value, "updateNo");
			return (Criteria) this;
		}

		public Criteria andUpdateNoGreaterThanOrEqualTo(String value) {
			addCriterion("update_no >=", value, "updateNo");
			return (Criteria) this;
		}

		public Criteria andUpdateNoLessThan(String value) {
			addCriterion("update_no <", value, "updateNo");
			return (Criteria) this;
		}

		public Criteria andUpdateNoLessThanOrEqualTo(String value) {
			addCriterion("update_no <=", value, "updateNo");
			return (Criteria) this;
		}

		public Criteria andUpdateNoLike(String value) {
			addCriterion("update_no like", value, "updateNo");
			return (Criteria) this;
		}

		public Criteria andUpdateNoNotLike(String value) {
			addCriterion("update_no not like", value, "updateNo");
			return (Criteria) this;
		}

		public Criteria andUpdateNoIn(List<String> values) {
			addCriterion("update_no in", values, "updateNo");
			return (Criteria) this;
		}

		public Criteria andUpdateNoNotIn(List<String> values) {
			addCriterion("update_no not in", values, "updateNo");
			return (Criteria) this;
		}

		public Criteria andUpdateNoBetween(String value1, String value2) {
			addCriterion("update_no between", value1, value2, "updateNo");
			return (Criteria) this;
		}

		public Criteria andUpdateNoNotBetween(String value1, String value2) {
			addCriterion("update_no not between", value1, value2, "updateNo");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("update_time is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("update_time is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("update_time =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("update_time <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("update_time >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("update_time >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("update_time <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("update_time <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterion("update_time in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterion("update_time not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("update_time between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("update_time not between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andAdderNoIsNull() {
			addCriterion("adder_no is null");
			return (Criteria) this;
		}

		public Criteria andAdderNoIsNotNull() {
			addCriterion("adder_no is not null");
			return (Criteria) this;
		}

		public Criteria andAdderNoEqualTo(String value) {
			addCriterion("adder_no =", value, "adderNo");
			return (Criteria) this;
		}

		public Criteria andAdderNoNotEqualTo(String value) {
			addCriterion("adder_no <>", value, "adderNo");
			return (Criteria) this;
		}

		public Criteria andAdderNoGreaterThan(String value) {
			addCriterion("adder_no >", value, "adderNo");
			return (Criteria) this;
		}

		public Criteria andAdderNoGreaterThanOrEqualTo(String value) {
			addCriterion("adder_no >=", value, "adderNo");
			return (Criteria) this;
		}

		public Criteria andAdderNoLessThan(String value) {
			addCriterion("adder_no <", value, "adderNo");
			return (Criteria) this;
		}

		public Criteria andAdderNoLessThanOrEqualTo(String value) {
			addCriterion("adder_no <=", value, "adderNo");
			return (Criteria) this;
		}

		public Criteria andAdderNoLike(String value) {
			addCriterion("adder_no like", value, "adderNo");
			return (Criteria) this;
		}

		public Criteria andAdderNoNotLike(String value) {
			addCriterion("adder_no not like", value, "adderNo");
			return (Criteria) this;
		}

		public Criteria andAdderNoIn(List<String> values) {
			addCriterion("adder_no in", values, "adderNo");
			return (Criteria) this;
		}

		public Criteria andAdderNoNotIn(List<String> values) {
			addCriterion("adder_no not in", values, "adderNo");
			return (Criteria) this;
		}

		public Criteria andAdderNoBetween(String value1, String value2) {
			addCriterion("adder_no between", value1, value2, "adderNo");
			return (Criteria) this;
		}

		public Criteria andAdderNoNotBetween(String value1, String value2) {
			addCriterion("adder_no not between", value1, value2, "adderNo");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table product
	 * 
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table product
	 *
	 * @mbggenerated do_not_delete_during_merge
	 */
	public static class Criteria extends GeneratedCriteria {

		protected Criteria() {
			super();
		}
	}

	public Page getPage() {
		return page;
	}

	public void setPage(Page page) {
		this.page = page;
	}

}